### ISSUE TITLE
Update Create Monitor page Design

### ISSUE THREAD

**Issue by cehicm** [Evil-Bees/Alertit#53]
This is what the Create Monitor (/dashboard/monitor/create) page looks like now.
We'd like to improve it's appearance, and are open to suggestions.

For inspiration, take a look at the Homepage and Status page

![image](https://user-images.githubusercontent.com/25206355/216428924-0acf8260-3bbe-4891-9147-ecaec56792e5.png)

**Comment by sarah-adewale** [comment]
Hi @cehicm i would like to contribute to this issue. Is it still open?

**Comment by nikolap994** [comment]
@sarah-adewale it's still open :) feel free to open PR

**Comment by sarah-adewale** [comment]
Okay, Thank you :)

**Comment by nikolap994** [comment]
@sarah-adewale  do we have any update here ?
If you are not interested anymore we will move this issue back to public so if anyone else is interested can take over.

**Comment by sarah-adewale** [comment]
@nikolap994 Apologies for not sending this in, i've had a family emergency for the past weeks that's why i haven't gotten around to it. I intend to work on it over this weekend and send in a pull request. I am still interested, but if you want to move it back to public i would understand. I'll still send in my pull request regardless. Thank you so much.

**Comment by nikolap994** [comment]
We will leave it up to you, thank you for feedback :)

**Comment by sarah-adewale** [comment]
really appreciate :)
